---
title: "Characterising information loss due to aggregating epidemic model outputs"
output: html_document
---

```{r set-up, include=FALSE}
# Set up Rmarkdown and workspace -----
library(here)
library(dplyr)
library(tidyr)
library(purrr)
library(scoringutils)
library(ggplot2)
library(cowplot)
knitr::opts_chunk$set(eval = TRUE, echo = FALSE,
                      message = FALSE, warning = FALSE,
                      eval.after = "fig.cap")
options(digits = 2)

local <- TRUE # FALSE = download data from hub git remote, TRUE = use copy in this repo

# import functions
source(here("code", "import-results.R"))
source(here("code", "create-ensembles.R"))

# Quantiles for vincent & LOP ensembles (standard hub submission format)
quantiles <- c(0.01, 0.025, 
               seq(0.05, 0.95, by = 0.05), 
               0.975, 0.99)

# Prettier formatting -----
# targets
target_levels <- c("BE inc case", "NL inc case", "ES inc case", "BE inc death", "NL inc death")
target_labels <- c("Belgium cases", "Netherlands cases", "Spain cases", "Belgium deaths", "Netherlands deaths")
names(target_levels) <- target_labels
names(target_labels) <- target_levels

# Quantiles for plotting
quantile_plotting <- paste0("q", c(0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99))

# colours for scenarios
scenario_colours <- c("A" = "#e66101",
                      "B" = "#ca0020",
                      "C" = "#0571b0",
                      "D" = "#5e3c99",
                      "Weighted" = "grey50")
theme_set(theme_cowplot())
```


## Results

```{r load-samples}
# Load samples from all models together with observed data
results <- import_projections(round = 2, n_model_min = 3,
                              local = local) |> 
  mutate(target = ordered(x = paste(location, target_variable),
                          levels = target_levels,
                          labels = target_labels))
```

```{r create-simple-ensembles, warning=FALSE}
# Create two simple ensembles ("Sample", "Quantile")
simple_ensembles <- create_simple_ensembles(results = results, 
                                            quantiles = quantiles)
# Create linear pool ensemble
linear_pool_ensemble <- create_lop_ensemble(results = results,
                                            quantiles = quantiles)
ensembles <- bind_rows(simple_ensembles, linear_pool_ensemble) |> 
  # Round values to integers (LOP produces decimals)
  mutate(value = round(value, digits = 0),
         # organise targets
         target = ordered(x = paste(location, target_variable),
                          levels = target_levels,
                          labels = target_labels)) |> 
  select(-c(n, output_type))
```

#### Comparison of all ensembles

Figure 1

```{r plot-simple, warning=FALSE, fig.dim=c(12,8)}
# Reshape data for plotting -----
  # ensembles
  plot_ensembles <- ensembles |>
    filter(quantile %in% quantile_plotting) |> 
    pivot_wider(names_from = quantile) |>
    mutate(median = q0.5) |>
    select(-q0.5)

  # samples
  plot_samples <- results |>
    mutate(model_sample = paste(location, target_variable, scenario_id,
                                model, sample,
                                sep = "-"),
           model = "None") |> # relabel model to None
    rename(q0.5 = value_100k) |>
    select(location, target_variable,
           target_end_date, scenario_id,
           model, model_sample, q0.5)

  # combine data and observations
  ensembles_samples_plot <- bind_rows(plot_ensembles, plot_samples) |>
    left_join(distinct(results,
                       location, target_variable,
                       target_end_date, obs_100k),
              by = c("location", "target_variable", "target_end_date"))

  # Format for plotting -----------------------------------------------------
  ensembles_samples_plot <- ensembles_samples_plot |>
    # set order for facet rows
    mutate(model = ordered(model,
                           levels = c("None",
                                      "Trajectories",
                                      "Linear pool",
                                      "Quantiles"),
                           labels = c("i. All models' simulated trajectories",
                                      "ii. Ensemble from trajectories",
                                      "iv. Linear pool ensemble",
                                      "iii. Ensemble from models' quantiles")),
      # avoid overplotting observed data
           obs_100k = ifelse(model %in% c("Quantiles", 
                                          "Trajectories", "Linear pool"), 
                             NA, obs_100k))

  # Plot --------------------------------------------------------------
  plot_ensembles_samples <- ensembles_samples_plot |>
    mutate(target = ordered(x = paste(location, target_variable),
                          levels = target_levels,
                          labels = target_labels)) |>
    # filter(target == set_target) |>
    ggplot(aes(x = target_end_date,
               fill = scenario_id, col = scenario_id)) +
    # ----- Geoms
    # ensembles
    geom_ribbon(aes(ymin = q0.01, ymax = q0.99),
                alpha = 0.1, col = NA) +
    geom_ribbon(aes(ymin = q0.25, ymax = q0.75),
                alpha = 0.4, col = NA) +
    geom_line(aes(y = median), size = 1) +
    # model samples
    geom_line(aes(y = q0.5, group = model_sample),
              alpha = 0.1) +
    # observed data as points
    geom_point(aes(y = obs_100k),
               colour = "grey20", size = 0.6, show.legend = FALSE) +
    # ----- Structure
    # facets
    facet_grid(rows = vars(target), cols = vars(model),
               scales = "free", switch = "y") +
    # labels
    labs(x = NULL, y = "Incidence per 100k",
         colour = "Scenario", fill = "Scenario") +
    # colours and scales
    scale_colour_manual(values = scenario_colours,
                        aesthetics = c("colour", "fill")) +
    scale_x_date(breaks = "3 month", date_labels = "%b '%y") +
    # theme
    theme(legend.position = "bottom",
          strip.background = element_blank(),
          strip.placement = "outside",
          strip.text = element_text(face = "bold", size = 10))

ggsave(filename = here("output", "figures", "figure-1.jpg"),
       plot = plot_ensembles_samples, 
       width = 10, height = 8)
  
plot_ensembles_samples
```

#### Conditioning samples on an increasing amount of data

```{r weekly-ensembles, warning=FALSE}
# Create set of weekly ensembles with progressively increasing observed data
weekly <- create_weekly_ensembles(results)
weekly_ensembles <- weekly$ensembles |>
  mutate(weighting = ifelse(scenario_id == "Unweighted", "Unweighted", 
                            paste0(horizon, " weeks ago")),
         target = ordered(x = paste(location, target_variable),
                            levels = target_levels,
                            labels = target_labels))
# Include observed data
weekly_ensembles <- weekly_ensembles |>
    full_join(results |>
                distinct(target, target_end_date, obs_100k), 
              by = c("target", "target_end_date"))
```


```{r plot-weekly-ensembles, warning=FALSE, fig.dim=c(8,8)}
# Plot -------------------------------------------
# set up colours
horizon_cols <- c("16 weeks ago" = "#a1dab4", 
                  "8 weeks ago" = "#41b6c4", 
                  "4 weeks ago" = "#225ea8",
                  "Unweighted" = "grey")
# Plot
# ----- Shape data for plotting
weekly_ensemble_plotdata <- weekly_ensembles |>
  mutate(target = ordered(x = paste(location, target_variable),
                          levels = target_levels,
                          labels = target_labels),
         weighting = ordered(x = weighting,
                             levels = c("16 weeks ago",
                                        "8 weeks ago",
                                        "4 weeks ago",
                                        "Unweighted"))) |> 
  select(-c(location, target_variable)) |> 
  group_by(target, forecast_date, target_end_date) |> 
  filter(quantile %in% c("q0.01", "q0.25", "q0.5", "q0.75", "q0.99")) |> 
  pivot_wider(values_from = value,
                names_from = quantile) |>
  rename(median = q0.5) 
# split out weighted/unweighted so they can have separate geoms
weekly_ensemble_weighted <- weekly_ensemble_plotdata |>
  filter(weighting %in% c("16 weeks ago", "8 weeks ago", "4 weeks ago")) 
weekly_ensemble_unweighted <- weekly_ensemble_plotdata |>
  filter(weighting == "Unweighted") #& horizon %in% c(4,8,16)

# ----- Plot
weekly_ensemble_plot <- weekly_ensemble_weighted |> 
    ggplot(aes(x = target_end_date,
               group = weighting,
               col = weighting,
               fill = weighting)) +
    # ----- Geoms
    # unweighted ensemble
    geom_ribbon(aes(ymin = q0.01, ymax = q0.99),
                col = NA,
                alpha = 0.3, 
                data = weekly_ensemble_unweighted) +
    # weighted ensembles
    geom_ribbon(aes(ymin = q0.01, ymax = q0.99),
                col = NA,
                alpha = 0.3) +
    geom_ribbon(aes(ymin = q0.25, ymax = q0.75),
                col = NA,
                alpha = 0.6) +
    #geom_line(aes(y = median), alpha = 0.8, lwd = 1) +
    # observed data as points
    geom_point(aes(y = obs_100k),
               colour = "grey20", size = 0.6,
               show.legend = FALSE) +
    # show start date of weighted forecasting
    geom_vline(xintercept = as.Date("2022-08-27"),
               lty = 2) +
    # ----- Structure
    # facets
    facet_grid(rows = vars(target),
               scales = "free", switch = "y") +
    # labels
    labs(x = NULL, y = "Incidence per 100k",
         fill = "Conditioned on data up to",
         col = "Conditioned on data up to") +
    # scales
    scale_x_date(limits = c(min(results$target_end_date),
                            as.Date("2023-03-11")),
                 breaks = "1 month", date_labels = "%b '%y") +
    scale_colour_manual(values = horizon_cols,
                        aesthetics = c("fill", "colour")) +
    # theme
    theme(legend.position = "bottom",
          strip.background = element_blank(),
          strip.placement = "outside",
          strip.text = element_text(face = "bold", size = 8))

ggsave(filename = here("output", "figure-2.jpg"),
       plot = weekly_ensemble_plot, 
       width = 6, height = 8)

weekly_ensemble_plot
```

```{r score-weekly-ensembles}
# Format forecasts and observations for scoring
forecasts <- weekly_ensembles |>
  mutate(model = weighting,
         quantile = as.numeric(gsub(pattern = "q", replacement = "",
                                    x = quantile)),
         forecast_date = as.Date(forecast_date)) |>
  rename(prediction = value,
         true_value = obs_100k) |>
  select(-c(scenario_id, target)) |>
  # remove where no data (after March 2023)
  filter(target_end_date <= as.Date("2023-03-04") &
           !is.na(model))

# Score forecasts on log scale
scores <- forecasts |>
  mutate(
    scale = "log",
    true_value = log(true_value + 1e-05), #1/100000
    prediction = log(pmax(prediction, 0) + 1e-05)) |>
  score(metrics = c("interval_score")) |>
  summarise_scores(by = c("location", "target_variable",
                          "target_end_date", "forecast_date",
                          "model", "scale"),
                   na.rm = TRUE)

# Score all forecasts relative to each other (pairwise) -----
score_pairwise <- pairwise_comparison(scores = scores,
                                      metric = "interval_score",
                                      baseline = "Unweighted",
                                      by = c("model", "scale",
                                             "location", "target_variable")) |>
  filter(compare_against == "Unweighted" & 
           model >= 0) |>
  select(model, scale, location, target_variable, rel_wis = scaled_rel_skill) |> 
  mutate(target = paste(location, target_variable),
         target_label = ifelse(model == "27 weeks ago", target, NA),
         weeks_used = as.numeric(substr(start = 1, stop = 2, model)))

# Summary stats -----
print("Summary of all weighted forecasts' relative WIS")
summary(score_pairwise$rel_wis)
```
```{r plot-scored-weekly-ensembles, warning=FALSE}
# Plot --------------------------------------------------------------------
scores_plot <- score_pairwise |>
  # Plot
  ggplot(aes(x = weeks_used, y = rel_wis, col = target)) +
  geom_line() +
  geom_hline(yintercept = 1, lty = 2, col = horizon_cols["Unweighted"]) +
  geom_vline(xintercept = 4, lty = 2, lwd = 0.8, col = horizon_cols["4 weeks ago"]) +
  geom_vline(xintercept = 8, lty = 2, lwd = 0.8, col = horizon_cols["8 weeks ago"]) +
  geom_vline(xintercept = 16, lty = 2, lwd = 0.8, col = horizon_cols["16 weeks ago"]) +
  scale_x_continuous(breaks = c(4,8,16)) +
  scale_color_brewer(type = "qual", palette = "Dark2") +
  ggrepel::geom_text_repel(aes(label = target_label, rm.na = TRUE),  
                            segment.colour = NA, nudge_x = 3) +
  labs(y = "Relative WIS", 
       x = "Number of weeks' performance used for trajectory weighting",
       col = "Target") +
  theme(legend.position = "none")

# title = "Performance of weighted forecasts by weeks' data used",
# caption = "Forecasting performance of ensembles, forecasting weekly over the future period (to 22 July 2023) \n using increasing weeks of data to weight each trajectory. Performance measured by the weighted interval score (WIS) of each weighted ensemble, relative to an equivalent ensemble with equal weights for each trajectory (reference line at 1)"

ggsave(filename = here("output", "figure-3.jpg"), 
       plot = scores_plot,
       width = 6, height = 8)

scores_plot
```

# Supplementary Information

SI Figure 1: Difference between uncertainty ranges

```{r width-ensembles, fig.width = 8}
get_interval_widths <- function(ensemble) {
  interval_ensembles <- ensemble |>
  mutate(quantile = as.numeric(as.character(sub("q0", "", quantile))),
         interval = round(2 * abs(0.5 - quantile), 2),
         type = if_else(quantile <= 0.5, "lower", "upper"),
         target = paste(location, gsub("inc ", "", 
                                       target_variable)))
duplicate_median <- interval_ensembles |>
  filter(quantile == 0.5) |>
  mutate(type = "upper")
width <- interval_ensembles |>
  bind_rows(duplicate_median) |>
  select(-quantile) |>
  pivot_wider(names_from = "type") |>
  # Average across all scenarios and dates
  group_by(target, model, interval) |>
  summarise(upper = mean(upper),
            lower = mean(lower),
            .groups = "drop")
return(width)
}

# Look at unweighted ensemble comparison
width <- get_interval_widths(ensembles)
width_plot <- width |>
  ggplot(aes(x = interval,
             ymin = lower, ymax = upper,
             group = model,
             colour = model, fill = model)) +
  geom_ribbon(alpha = 0.25) +
  geom_linerange(alpha = 0.25) +
  geom_point(aes(y = lower), alpha = 0.5) +
  geom_point(aes(y = upper), alpha = 0.5) +
  scale_colour_brewer(palette = "Set1") +
  scale_fill_brewer(palette = "Set1") +
  labs(y = "Mean lower and upper incidence per 100k",
       x = "Interval width around median",
       fill = "Ensemble source:",
       colour = "Ensemble source:") +
  facet_grid(rows = vars(target),
             scales = "free_y", switch = "y") +
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(face = "bold", size = 8))

# Repeat for comparing weighted ensembles
earliest_target <- filter(weekly_ensembles, horizon == 16) |>
  pull(target_end_date) |> min()
latest_target <- filter(weekly_ensembles, horizon == 4) |>
  pull(target_end_date) |> max()
weekly_widths <- weekly_ensembles |>
  mutate(model = weighting) |>
  filter(between(target_end_date, earliest_target, latest_target)) |>
  get_interval_widths()
weekly_width_upper <- weekly_widths |>
  select(-lower) |>
  group_by(target, interval) |>
  pivot_wider(names_from = model, values_from = upper) |>
  mutate(diff = (`4 weeks ago` - `16 weeks ago`)/`16 weeks ago`)

weekly_width_plot <- weekly_widths |>
  filter(model %in% c("4 weeks ago", "8 weeks ago", "16 weeks ago")) |> 
  ggplot(aes(x = interval,
             ymin = lower, ymax = upper,
             group = model,
             colour = model, fill = model)) +
  geom_ribbon(alpha = 0.25) +
  geom_linerange(alpha = 0.25) +
  geom_point(aes(y = lower), alpha = 0.5) +
  geom_point(aes(y = upper), alpha = 0.5) +
  scale_colour_manual(values = horizon_cols, aesthetics = c("fill", "colour")) +
  labs(x = "Interval width around median",
       y = NULL,
       fill = "Conditioned on data:",
       colour = "Conditioned on data:",
       caption = "The 52-week mean of incidence per 100,000 population across all time points and scenarios, showing mean central prediction intervals at increasing distances from the median (interval width), by aggregation method (A) or weighting (B). The median estimate for each ensemble has 0 interval width (x-axis), with uncertainty increasing until an interval width at 0.98 represents the 1%-99% credibility interval around the median.") +
  facet_grid(rows = vars(target),
             scales = "free_y", switch = "y") +
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(face = "bold", size = 8))

title <- "SI Figure 1. Mean central prediction intervals at increasing distances from the median (interval width), by (A) aggregation method or (B) weeks’ data used in weighted ensemble."

combined_width_plot <- cowplot::plot_grid(width_plot,
                                          weekly_width_plot, 
                                          ncol = 2, 
                                          labels = "AUTO")

# Save/print
ggsave(filename = here("output", "figures", "SI-figure-1.pdf"),
       plot = combined_width_plot, 
       width = 12, height = 8)

combined_width_plot
```

## SI Figure 2: Summary performance of weighted ensembles 

```{r boxplot-scored-weekly-ensembles, warning=FALSE}
scores_boxplot <- score_pairwise |> 
  ggplot(aes(x = target, y = rel_wis, col = target)) +
  geom_boxplot() +
  geom_hline(yintercept = 1, lty = 2) +
  labs(x = NULL, y = "Relative WIS",
       title = "SI Figure 2. Performance of weighted forecasts",
     caption = "Distribution of forecast performance scores (relative WIS), of forecasts from \n model trajectories weighted using 0 through 27 weeks' available data. \n Performance is compared to an unweighted ensemble (reference line at 1)") +
  scale_color_brewer(palette = "Dark2") +
  theme(legend.position = "none")

ggsave(filename = here("output", "figures", "SI-figure-2.pdf"),
       plot = scores_boxplot, 
       width = 6, height = 4)
scores_boxplot
```

----------------------

```{r create-supplement}
# Add information on contributing teams
rmarkdown::render(here("output", "supplement",
                       "supplement-contributing-teams.Rmd"),
                  output_file = here("output", "supplement",
                                     "SI-contributing-teams.pdf"))
# Create a combined PDF supplement file
pdftools::pdf_combine(c(here("output", "figures", "SI-figure-1.pdf"),
              here("output", "figures", "SI-figure-2.pdf"),
              here("output", "supplement", "SI-contributing-teams.pdf"),
              here("output", "supplement", "Round 2 realtime report.pdf")),
            output = "Supplement.pdf")
```
