---
title: "Characterising information loss due to aggregating epidemic model outputs"
output: html_document
---

```{r set-up, include=FALSE}
# Document settings -----
knitr::opts_chunk$set(eval = TRUE, echo = FALSE,
                      message = FALSE, warning = FALSE,
                      eval.after = "fig.cap")
options(digits = 2)
# Workspace -----
library(here)
library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)
library(patchwork)
local <- TRUE # download or use saved data 
target_levels <- c("ES inc case", "BE inc case", "NL inc case", "BE inc death", "NL inc death")
target_labels <- c("ES cases", "BE cases", "NL cases", 
                   "BE deaths", "NL deaths")
names(target_levels) <- target_labels

# colours for scenarios
scenario_colours <- c("A" = "#e66101",
                      "B" = "#ca0020",
                      "C" = "#0571b0",
                      "D" = "#5e3c99",
                      "Weighted" = "grey50")
```


## Results

```{r load-samples}
# Load samples from all models
source(here("code", "import-results.R"))
results <- import_projections(round = 2, local = local, n_model_min = 3) |> 
  mutate(target = ordered(x = paste(location, target_variable),
                          labels = target_labels))
```
```{r compare-cumulative-peaks}
source("code/summarise/cumulative.R")
cumulative_plots <- plot_cumulative_summary(data = results_multi_country,
                                            truth = truth,
                                            compare_last_year = TRUE)
```


```{r create-ensembles, fig.height=8, fig.width=12}
# Create three ensembles ("Sample", "Quantile", "Weighted")
source(here("code", "create-ensembles.R"))
truncate_weeks <- 2 # scoring evaluation against all data -2 weeks before now
ensembles <- create_ensembles(results = results, 
                              truncate_weeks = truncate_weeks,
                              quantiles = c(0.01, 0.05, 0.25, 0.5, 
                                            0.75, 0.95, 0.99)) |> 
  mutate(target = ordered(x = paste(location, target_variable),
                          labels = target_labels))
# Plot: All targets' trajectories over time and by ensemble
source(here("code", "plot.R"))
plots <- purrr::map(target_levels,
                    ~ plot_ensemble_results(ensembles, results, 
                                            set_target = .x,
                                            scenario_colours = scenario_colours))

figure_1 <- wrap_plots(plots, 
           ncol = length(plots), 
           guides = "collect") &
  theme(legend.position = "top")

ggsave(filename = here("output", "figure-1.jpg"),
       plot = figure_1, height = 8, width = 12)

figure_1
```



```{r width-ensembles, fig.cap=width_plot_caption, fig.width = 12}
source(here("code", "compare-ensembles.R"))
ggsave(filename = here("output", "figure-2.jpg"),
       plot = width_plot, width = 12)
width_plot
```

```{r samples-weights, fig.width = 12}
# Score samples
source(here("code", "score-samples.R"))
samples_weighted <- score_samples(results = results, 
                                  truncate_weeks = truncate_weeks) |> 
  ungroup()

# summarise weights
weights <- samples_weighted |> 
  mutate(target = ordered(x = paste(location_name, target_variable),
                          labels = target_labels)) |> 
  group_by(target) |> 
  filter(horizon == 1)

weight_summary <- weights |> 
  summarise(n = n(),
            mean_weight = mean(weight),
            min = min(weight),
            q25 = quantile(weight, 0.25),
            q50 = median(weight),
            q75 = quantile(weight, 0.75),
            max = max(weight),
            weight = sum(weight))
weights_over_01 <- sum(weights$weight >= 0.001)
plot_sample_weights <- weights |> 
  ggplot(aes(x = target, y = weight * 100)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(aes(col = scenario_id), size = 0.5, alpha = 1) +
  scale_colour_manual(values = scenario_colours) +
  labs(x = NULL, y = "% weight of each sample", col = "Scenario") +
  theme_bw() +
  theme(legend.position = "bottom") +
  guides(color = guide_legend(override.aes = list(size = 2, alpha = 1)))

ggsave(filename = here("output", "figure-3.jpg"),
       plot = plot_sample_weights, width = 12)

text <- cat("When weighted by inverse MAE, no sample received more than `r max(weights$weight)*100`% weight (among n=`r nrow(weights)/length(unique(weights$target))` samples for each target).")

plot_sample_weights
```
`r weights_caption`

```{r end-projection-uncertainty}
proj_end <- ensembles |> 
  filter(scenario_id == "Weighted") |> 
  group_by(location, target_variable) |> 
  filter(target_end_date == max(target_end_date) & 
           quantile == "q0.99") |> 
  filter(value == max(value))

end_max <- results |> 
  group_by(location, target_variable) |>
  filter(target_end_date == max(target_end_date)) |> 
  filter(value_100k == max(value_100k))
```

